In [1]:
import pandas as pd
import numpy as np

In [2]:
# Load data
df = pd.read_csv('CAIT 2.0 Country Clean Technology Data-csv.csv')
df.head(10)

,Unnamed: 0,Unnamed: 1,Capacity,Unnamed: 3,Unnamed: 4,Unnamed: 5,Manufacturing Capacity,Unnamed: 7,Unnamed: 8,Unnamed: 9,Jobs,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,Country,Year,Cumulative Installed Solar PV Capacity (MW),Annual Additions of Installed Solar PV Capacit...,Cumulative Installed Wind Capacity (MW),Annual Additions of Installed Wind Capacity (MW),Annual Manufacturing Capacity of Silicon (Metr...,Annual Manufacturing Capacity of PV Cells (MW),Annual Manufacturing Capacity of PV Modules (MW),Annual Manufacturing Capacity of Wind Turbines...,Total Solar PV Jobs,Total Solar PV Manufacturing Jobs,Total Wind Jobs,Total Wind Manufacturing Jobs
1,China,2000,NaN,NaN,346,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,China,2001,NaN,NaN,402,56,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,China,2002,NaN,NaN,469,67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,China,2003,NaN,NaN,567,98,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,China,2004,62.1,10,764,197,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,China,2005,71,8.9,1260,496,NaN,253,373,781.5,NaN,NaN,NaN,NaN
7,China,2006,81,10,2559,1299,NaN,893,1054.5,1254.5,39500,NaN,NaN,NaN
8,China,2007,101,20,5910,3351,1500,2361,2597,4683.4,82800,NaN,NaN,NaN
9,China,2008,141,40,12020,6110,4500,5101,4470,10935.75,200000,NaN,NaN,NaN

#### Description of the columns

- Country: Country Name
- Year: year
- Cumulaive Installed Solar PV Capacity (MW): Cumulative amount energy can be produced by the solar system
- Annual Additions of Installed Solar PV Capacity (MW): the additional amount of energy that can be produced by solar system compare to last year
- Annual Manufacturing capacity of Sillicon (Metric Tons): amount of silicon can be produced in a year
- Annual Manufacturing Capacity of PV Cells (MW): the number of photovoltaic cells that can be produced in a year based on the amount of energy they can produce
- Annual Manufacturing Capacity of PV modules (MW): number of photovoltaic modules that can be manufactured in a year based on the amount of energy the would produce
- Annual Manufacturing of Wind Turbines (MW): the number of wind turbines that can be producecd in a year based on the amount of energy they output
- Total Solar PV Jobs: total number of solar photovoltaic jobs
- Total Wind Jobs: total number of wind energy jobs
- Total Manufacturing Jobs: total number of turbine manufacturing jobs